# Generated by Django 4.2.11 on 2026-02-17 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('class_applying', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('previous_school', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='admission_photos/')),
                ('entrance_date', models.DateField(blank=True, null=True)),
                ('entrance_time', models.CharField(blank=True, max_length=50, null=True)),
                ('entrance_venue', models.CharField(blank=True, max_length=200, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
