# Generated by Django 4.2.11 on 2026-02-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_entrancepreparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='marks_obtained',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='result_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='result_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Not Selected', 'Not Selected'), ('Waiting List', 'Waiting List')], default='Pending', max_length=20),
        ),
    ]
