# Generated by Django 4.2.11 on 2026-02-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_admissionapplication_marks_obtained_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_open', models.BooleanField(default=False)),
                ('result_published', models.BooleanField(default=False)),
                ('preparation_visible', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
