# Generated by Django 4.2.11 on 2026-02-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_admissionsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Admission Application', 'verbose_name_plural': 'Admission Applications'},
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='merit_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='marks_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
