# Generated by Django 4.2.11 on 2026-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_admissionapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionsettings',
            options={'verbose_name': 'Admission System Setting', 'verbose_name_plural': 'Admission System Settings'},
        ),
        migrations.AddField(
            model_name='admissionsettings',
            name='popup_image',
            field=models.ImageField(blank=True, help_text='Upload admission poster image (Bharna Khulyo banner).', null=True, upload_to='admission_popup/'),
        ),
        migrations.AddField(
            model_name='admissionsettings',
            name='popup_message',
            field=models.TextField(blank=True, help_text='Optional message to display below the popup image.'),
        ),
        migrations.AlterField(
            model_name='admissionsettings',
            name='admission_open',
            field=models.BooleanField(default=False, help_text='Tick to activate admission system and show popup on homepage.'),
        ),
        migrations.AlterField(
            model_name='admissionsettings',
            name='preparation_visible',
            field=models.BooleanField(default=False, help_text='Show entrance preparation materials to students.'),
        ),
        migrations.AlterField(
            model_name='admissionsettings',
            name='result_published',
            field=models.BooleanField(default=False, help_text='Allow students to check entrance results.'),
        ),
    ]
