# Generated by Django 4.2.11 on 2026-02-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('notice_image', models.ImageField(blank=True, null=True, upload_to='notices/')),
                ('is_popup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
