# Generated by Django 4.2.11 on 2026-02-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_primaryevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=6, unique=True)),
                ('prize', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
