# Generated by Django 4.2.11 on 2026-02-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_gamecontrol_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='prize',
        ),
        migrations.AddField(
            model_name='gamecontrol',
            name='winner_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
