# Generated by Django 4.2.11 on 2026-02-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_ticket_prize_gamecontrol_winner_selected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_winner',
            new_name='has_won',
        ),
        migrations.RemoveField(
            model_name='gamecontrol',
            name='winner_selected',
        ),
        migrations.AddField(
            model_name='gamecontrol',
            name='current_round',
            field=models.CharField(default='FIRST', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prize_type',
            field=models.CharField(choices=[('FIRST', 'First Prize'), ('SECOND', 'Second Prize'), ('THIRD', 'Third Prize'), ('NONE', 'None')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
