# Generated by Django 4.2.11 on 2026-02-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_rename_is_winner_ticket_has_won_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.RemoveField(
            model_name='gamecontrol',
            name='current_round',
        ),
    ]
