# Generated by Django 4.2.11 on 2026-02-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tickets', models.PositiveIntegerField()),
            ],
        ),
    ]
