# Generated by Django 4.2.11 on 2026-02-25 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0017_ticketgenerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('citizenship_no', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('experience', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('first_login', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
