# Generated by Django 4.2.11 on 2026-02-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='qualification',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='citizenship_no',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
