# Generated by Django 4.2.11 on 2026-02-25 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_groupleader_ticket_is_assigned_ticket_is_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_assigned',
            new_name='is_validated',
        ),
        migrations.RemoveField(
            model_name='groupleader',
            name='phone',
        ),
        migrations.CreateModel(
            name='TicketBulkValidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_list', models.TextField(help_text='Paste tickets separated by comma')),
                ('group_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.groupleader')),
            ],
        ),
    ]
