# Generated by Django 4.2.11 on 2026-02-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_rename_is_assigned_ticket_is_validated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('spin_count', models.PositiveIntegerField(default=0)),
                ('first_prize_given', models.BooleanField(default=False)),
                ('second_prize_given', models.BooleanField(default=False)),
                ('third_prize_given', models.BooleanField(default=False)),
                ('fourth_prize_given', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='matched_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prize_position',
            field=models.PositiveIntegerField(blank=True, help_text='1=First, 2=Second, 3=Third, 4=Fourth', null=True),
        ),
    ]
