# Generated by Django 4.2.11 on 2026-02-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_gamesession_ticket_is_winner_ticket_matched_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
