# Generated by Django 4.2.11 on 2026-03-01 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_gamesession_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='allow_first_prize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='allow_fourth_prize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='allow_second_prize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='allow_third_prize',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SpinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gamesession')),
            ],
        ),
    ]
