# Generated by Django 4.2.11 on 2026-03-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_gamesession_allow_first_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='forced_prize_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='forced_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forced_for_session', to='school.ticket'),
        ),
    ]
